=====================Daily USe English Words with Hindi Meaning List===========================
refrence link-: https://hindimediumhelp.blogspot.com/2020/05/daily-use-vocabulary-words.html

1) till now (abhi tak)
2) still (abhi bhi)
3) not yet (abhi nhi)
4) willpower (iccha shakti)
5) Encourage (himmat badana)
6) Rely (believe someone or depend)
7) burden
8) Praise (tarif karna)
9) Disciminate (bhedhbhav karna / pachpat karna/ diffrence karna )
10) Dull (sust)
11) sneez (chhikna)
12) Deceive (dhoka dena)
13) Tolerate (sahan karna)
14) conveinent (suvidha janak)
15) forgive(mafi magna)
16) biting nails (nakhun chabana)
17) Superior (behatar)
18) Slightly (littile bit)
19) Repent (pachatawa karna)
20) For how long 
21) Remind me one thing (ek cheej yad dilana)
22) Literally (sachmuch/sahi mai)
23) Deny (mana karna)
24) Blunt (muh fat)
25) Influence (asar/ prabhaw)
26) Give UP (har man lena)
27) Admire (sarahana karna)
28) Somehow (jaise taise)
29) Misguide (bahkana)
30) oh shit
31) Rude (batamizi say)
32) Unfortuanetly (durbhagya say)
33) In a while( dhodi der mai)
34) for a while (dhodi der ke liye)
35) beleive it or not (mano ya na mano)
36) circumstance (situations)
37) Native (mul/deshi)
38) Ego (ahnakar arogance)
39) attitude (rawaya)
40) go Ahead (aage ki aur bado)
41) to defame (badnam karna)
42) dominate (hawi hona)
43) debat (bahas or argu)
44) Concern (chinta ka subject)
45) Even (yha tak ki)
46) Rather (balki)
47) such (aisa hai)
48) Beyond (pare)
49) let (karne dena)
50) accomplish (end karna/ samaapt karana)
51) declutter (अस्वीकरण)
52) enthusiasm (josh)
53) dispite (isake baavajood)
54) collaborate (sahayog/सहयोग)
55) barrier (intrrupt)
56) maid (नौकरानी)
57) get up (jagana)
58) be humble (विनम्र होना)
59) herself (स्वयं)
60) ourself (हम स्वयं)
61) wheather (कहीं)
62) either (दोनों में से एक)
63) apart from (के अलावा)
64) I hope so (मुझे आशा है)
65) determine (ठानना, तय करना)
66) bother (परेशानी)
67) worth (लायक)
68) perception (अनुभूति)
69) conquered (विजय प्राप्त की)
70) often (अक्सर)
71) pretend (बहाना करना)
72) miserable (दुखी)
73) humality (विनम्रता)
74) devote (समर्पित)
75) healing (घाव भरने वाला)
76) Faith (aastha)
77) perceive (समझना)
78) grab (लपकना)
79) being (हो रहा)
80) often (bar bar)