=====================Daily USe English Words with Hindi Meaning List===========================
refrence link-: https://hindimediumhelp.blogspot.com/2020/05/daily-use-vocabulary-words.html

1) till now (abhi tak)
2) still (abhi bhi)
3) not yet (abhi nhi)
4) willpower (iccha shakti)
5) Encourage (himmat badana)
6) Rely (believe someone or depend)
7) burden
8) Praise (tarif karna)
9) Disciminate (bhedhbhav karna / pachpat karna/ diffrence karna )
10) Dull (sust)
11) sneez (chhikna)
12) Deceive (dhoka dena)
13) Tolerate (sahan karna)
14) conveinent (suvidha janak)
15) forgive(mafi magna)
16) biting nails (nakhun chabana)
17) Superior (behatar)
18) Slightly (littile bit)
19) Repent (pachatawa karna)
20) For how long 
21) Remind me one thing (ek cheej yad dilana)
22) Literally (sachmuch/sahi mai)
23) Deny (mana karna)
24) Blunt (muh fat)
25) Influence (asar/ prabhaw)
26) Give UP (har man lena)
27) Admire (sarahana karna)
28) Somehow (jaise taise)
29) Misguide (bahkana)
30) oh shit
31) Rude (batamizi say)
32) Unfortuanetly (durbhagya say)
33) In a while( dhodi der mai)
34) for a while (dhodi der ke liye)
35) beleive it or not (mano ya na mano)
36) circumstance (situations)
37) Native (mul/deshi)
38) Ego (ahnakar arogance)
39) attitude (rawaya)
40) Ahead (aage ki aur)
41) to defame (badnam karna)
42) dominate (hawi hona)
43) debat (bahas or argu)
44) Concern (chinta ka subject)
45) Even (yha tak ki)
46) Rather (balki)
47) such (aisa hai)
48) Beyond (pare)
49) let (karne dena)
50) accomplish (end karna/ samaapt karana)
51) declutter (अस्वीकरण)
52)
53) dispite (isake baavajood)